;; generated using http://alexpogosyan.com/color-theme-creator/
(defun my-supercool-theme ()
  (interactive)
  (color-theme-install
   '(my-supercool-theme
      ((background-color . "#4d4d4d")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#333333")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#000000" :background "#666666"))))
     (region ((t (:background "#999999"))))
     (font-lock-builtin-face ((t (:foreground "#ebd87a"))))
     (font-lock-comment-face ((t (:foreground "#9e9e9e"))))
     (font-lock-function-name-face ((t (:foreground "#ccffee"))))
     (font-lock-keyword-face ((t (:foreground "#bdbdbd"))))
     (font-lock-string-face ((t (:foreground "#b8d7ff"))))
     (font-lock-type-face ((t (:foreground"#d5adff"))))
     (font-lock-variable-name-face ((t (:foreground "#f6bbbb"))))
     (minibuffer-prompt ((t (:foreground "#99b5ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'my-supercool-theme)
