
(defun sweyla714411 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/714411/"
  (interactive)
  (color-theme-install
   '(sweyla714411
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#F3C74C"))))
     (font-lock-constant-face ((t (:foreground "#F3AB71"))))
     (font-lock-builtin-face ((t (:foreground "#A66900"))))
     (font-lock-function-name-face ((t (:foreground "#FFB200"))))
     (font-lock-variable-name-face ((t (:foreground "#CF5486"))))
     (font-lock-keyword-face ((t (:foreground "#FF1005"))))
     (font-lock-string-face ((t (:foreground "#ACFE00"))))
     (font-lock-doc-string-face ((t (:foreground "#ACFE00"))))
     (font-lock-type-face ((t (:foreground "#D7C906"))))
     )))

(provide 'sweyla714411)
