
(defun sweyla855404 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/855404/"
  (interactive)
  (color-theme-install
   '(sweyla855404
     ((background-color . "#000C00")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#ACCF95"))))
     (font-lock-constant-face ((t (:foreground "#5467B9"))))
     (font-lock-builtin-face ((t (:foreground "#E1A55E"))))
     (font-lock-function-name-face ((t (:foreground "#FF0014"))))
     (font-lock-variable-name-face ((t (:foreground "#D91000"))))
     (font-lock-keyword-face ((t (:foreground "#FF6864"))))
     (font-lock-string-face ((t (:foreground "#87144C"))))
     (font-lock-doc-string-face ((t (:foreground "#87144C"))))
     (font-lock-type-face ((t (:foreground "#B7732A"))))
     )))

(provide 'sweyla855404)
