
(defun sweyla427593 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/427593/"
  (interactive)
  (color-theme-install
   '(sweyla427593
     ((background-color . "#FCFAFE")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#C4B437"))))
     (font-lock-constant-face ((t (:foreground "#BA6C69"))))
     (font-lock-builtin-face ((t (:foreground "#945094"))))
     (font-lock-function-name-face ((t (:foreground "#7EC43F"))))
     (font-lock-variable-name-face ((t (:foreground "#7C9470"))))
     (font-lock-keyword-face ((t (:foreground "#849478"))))
     (font-lock-string-face ((t (:foreground "#94945A"))))
     (font-lock-doc-string-face ((t (:foreground "#94945A"))))
     (font-lock-type-face ((t (:foreground "#FB7D2C"))))
     )))

(provide 'sweyla427593)
