
(defun sweyla769946 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/769946/"
  (interactive)
  (color-theme-install
   '(sweyla769946
     ((background-color . "#0F0004")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#F53278"))))
     (font-lock-constant-face ((t (:foreground "#FFC243"))))
     (font-lock-builtin-face ((t (:foreground "#FF8E6F"))))
     (font-lock-function-name-face ((t (:foreground "#FF6F00"))))
     (font-lock-variable-name-face ((t (:foreground "#B79300"))))
     (font-lock-keyword-face ((t (:foreground "#FF0434"))))
     (font-lock-string-face ((t (:foreground "#CF38FF"))))
     (font-lock-doc-string-face ((t (:foreground "#CF38FF"))))
     (font-lock-type-face ((t (:foreground "#7DF700"))))
     )))

(provide 'sweyla769946)
