
(defun sweyla328020 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/328020/"
  (interactive)
  (color-theme-install
   '(sweyla328020
     ((background-color . "#FFFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#FF3280"))))
     (font-lock-constant-face ((t (:foreground "#C82279"))))
     (font-lock-builtin-face ((t (:foreground "#FF3A00"))))
     (font-lock-function-name-face ((t (:foreground "#F99C08"))))
     (font-lock-variable-name-face ((t (:foreground "#8DC443"))))
     (font-lock-keyword-face ((t (:foreground "#4FB895"))))
     (font-lock-string-face ((t (:foreground "#FF0051"))))
     (font-lock-doc-string-face ((t (:foreground "#FF0051"))))
     (font-lock-type-face ((t (:foreground "#6A6E45"))))
     )))

(provide 'sweyla328020)
